name: Publish to npm

on:
  push:
    branches:
      - master 

jobs:
  check_if_version_upgraded:
    name: Check if version upgrade
    # When someone forks the repo and opens a PR we want to enables the tests to be run (the previous jobs)
    # but obviously only us should be allowed to release.
    # In the following check we make sure that we own the branch this CI workflow is running on before continuing.
    # Without this check, trying to release would fail anyway because only us have the correct secret.NPM_TOKEN but
    # it's cleaner to stop the execution instead of letting the CI crash.
    if: |
        github.event_name == 'push' || 
        github.event.pull_request.head.repo.owner.login == github.event.pull_request.base.repo.owner.login
    runs-on: ubuntu-latest
    outputs:
        from_version: ${{ steps.step1.outputs.from_version }}
        to_version: ${{ steps.step1.outputs.to_version }}
        is_upgraded_version: ${{ steps.step1.outputs.is_upgraded_version }}
        is_pre_release: ${{steps.step1.outputs.is_pre_release }}
    steps:
        - uses: garronej/ts-ci@v2.1.0
          id: step1
          with:
              action_name: is_package_json_version_upgraded
              branch: ${{ github.head_ref || github.ref }}

  publish:
    runs-on: ubuntu-latest
    needs: check_if_version_upgraded
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn

      - name: Build package
        run: yarn build

      - name: Customize package
        run: |
            chmod +x custom/prepublish.sh
            custom/prepublish.sh

      - name: Publish to npm
        run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
